// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlGw8flECK1hCNTbvo0UUQgG1KeLnH2U',
    appId: '1:443595974015:web:87331b1b9600758ec2e64a',
    messagingSenderId: '443595974015',
    projectId: 'spotify-a5d0a',
    authDomain: 'spotify-a5d0a.firebaseapp.com',
    storageBucket: 'spotify-a5d0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQM6scd_tvd0iHdGnjPPyNdhjJAf9bQ_Q',
    appId: '1:443595974015:android:50ddd506a667b4bdc2e64a',
    messagingSenderId: '443595974015',
    projectId: 'spotify-a5d0a',
    storageBucket: 'spotify-a5d0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhc3_JktgB_PEoen7mJ1-IBvTBANKOck',
    appId: '1:443595974015:ios:a3c422fd8604c63fc2e64a',
    messagingSenderId: '443595974015',
    projectId: 'spotify-a5d0a',
    storageBucket: 'spotify-a5d0a.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhc3_JktgB_PEoen7mJ1-IBvTBANKOck',
    appId: '1:443595974015:ios:a3c422fd8604c63fc2e64a',
    messagingSenderId: '443595974015',
    projectId: 'spotify-a5d0a',
    storageBucket: 'spotify-a5d0a.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVlGw8flECK1hCNTbvo0UUQgG1KeLnH2U',
    appId: '1:443595974015:web:aa49652c97f9c491c2e64a',
    messagingSenderId: '443595974015',
    projectId: 'spotify-a5d0a',
    authDomain: 'spotify-a5d0a.firebaseapp.com',
    storageBucket: 'spotify-a5d0a.firebasestorage.app',
  );
}
